---
- name: Testing andrewrothstein.kes
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'kes --verison'
      ansible.builtin.command: kes --version
      changed_when: false
      register: kes_test_output
    - name: Output from 'kes --version'
      ansible.builtin.debug:
        msg: '{{ kes_test_output.stdout }}'
