---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/kes --version
    register: kes_test_output
  - name: kes --version
    debug:
      msg: '{{ kes_test_output.stdout }}'
