---
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Downloading {{ kes_url }} to {{ kes_installed_exe }}
  become: true
  become_user: root
  ansible.builtin.get_url:
    url: '{{ kes_url }}'
    dest: '{{ kes_installed_exe }}'
    checksum: '{{ kes_checksum }}'
    mode: '755'
- name: Linking {{ kes_installed_link }} to {{ kes_installed_exe }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ kes_installed_exe }}'
    dest: '{{ kes_installed_link }}'
    state: link
